export const ENV = {
  DB_PORT: 'DB_PORT',
  DB_HOST: 'DB_HOST',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
  KAFKA_ADDRESS: 'KAFKA_ADDRESS',
  KAFKA_CLIENT_ID: 'KAFKA_CLIENT_ID',
  KAFKA_GROUP_ID: 'KAFKA_GROUP_ID',
  KAFKA_TASKS_TOPIC: 'KAFKA_TASKS_TOPIC',
};
